// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:string, arg2?:string[]):Promise<string>;

export function OpenSettings():Promise<void>;

export function SelectLocalFiles():Promise<string[]>;

export function SavePastedImage(dataURLOrBase64:string):Promise<string>;
