// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1, arg2) {
  return window['go']['main']['App']['Chat'](arg1, arg2);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function SelectLocalFiles() {
  return window['go']['main']['App']['SelectLocalFiles']();
}

export function SavePastedImage(arg1) {
  return window['go']['main']['App']['SavePastedImage'](arg1);
}
