// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {platformapi} from '../models';

export function Chat(arg1:string,arg2:Array<string>):Promise<string>;

export function CheckForUpdates():Promise<main.CheckUpdateResult>;

export function GetAuthState():Promise<main.AuthState>;

export function GetBackendStatus():Promise<platformapi.BackendStatus>;

export function GetChatPreflightState():Promise<main.ChatPreflightState>;

export function GetOfficialAccessState():Promise<platformapi.OfficialAccessState>;

export function GetOfficialPanelSnapshot():Promise<main.OfficialPanelSnapshot>;

export function GetVersion():Promise<string>;

export function HasPendingUpdate():Promise<boolean>;

export function ListAuthAgreements():Promise<Array<platformapi.AgreementDocument>>;

export function ListOfficialModels():Promise<Array<platformapi.OfficialModel>>;

export function OpenSettings():Promise<void>;

export function SavePastedImage(arg1:string):Promise<string>;

export function SelectLocalFiles():Promise<Array<string>>;

export function SignIn(arg1:string,arg2:string):Promise<main.AuthState>;

export function SignOut():Promise<void>;

export function SignUp(arg1:string,arg2:string,arg3:string):Promise<main.AuthState>;

export function SignUpWithAgreements(arg1:string,arg2:string,arg3:string,arg4:Array<platformapi.AgreementDocument>):Promise<main.AuthState>;
